name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
   test_image:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Docker Build
       run: docker build . --file Dockerfile --tag testrepo/testimage:latest
     - uses: anchore/scan-action@v1
       with:
         image-reference: "testrepo/testimage:latest"
         dockerfile-path: "./Dockerfile"
         fail-build: true