name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
   test_image:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
#     - name: Docker Build
#       run: docker build . --file Dockerfile --tag testrepo/testimage:latest

# synk
     - uses: actions/checkout@master
     - uses: snyk/actions/setup@master
     - uses: actions/setup-go@v1
       with:
        go-version: "1.13"
     - name: Snyk auth
       run: snyk test
       env:
         SYNK_TOKEN: ${{ secrets.SNYK_TOKEN }}


     - name: Login to Docker Hub
       if: failure() && steps.scan.outcome == 'success'
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}