name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
   test_image:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Docker Build
       run: docker build . --file Dockerfile --tag testrepo/testimage:latest

     - name: Start Docker Container
       run: docker run -d --name my-webserver -p 8080:80 testimage

     - name: Run Tests
       run: curl http://localhost:8080

     - name: Stop Docker container
       run: docker stop my-webserver

     - name: Login to Docker Hub
       if: success()
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}