name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
   test_image:
     runs-on: raspberrypi
     steps:
     - uses: actions/checkout@v1
     - name: Docker Build
       run: sudo docker build . --file Dockerfile -t vulnerable_app

     - name: Start Docker Container
       run: sudo docker run -d --name vulnerable_app -p 8080:80 vulnerable_app

     - name: Run Tests
       run: curl http://localhost:8080

     - name: Run OWASP ZAP
       uses: zaproxy/action-baseline@v0.12.0
       with:
           target: "http://localhost:8080"
           report-type: "json"
           report-name: "zap_report.json"

     - name: Stop Docker container
       run: sudo docker stop vulnerable_app

     - uses: anchore/scan-action@v1
       id: scan
       with:
         image-reference: "vulnerable_app:latest"
         dockerfile-path: "./Dockerfile"
         fail-build: true

     - name: Login to Docker Hub
       if: success()
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Push to DockerHub
#       run: sudo docker push jakob999/vulnerable_app:latest

     - name: Delete Container
       run: sudo docker rm vulnerable_app

     - name: Delete Image
       run: sudo docker rmi vulnerable_app
