name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  test_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag testrepo/testimage:latest
    - uses: anchore/scan-action@v1
      id: anchore_scan
      with:
        image-reference: "testrepo/testimage:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: true

  build-and-push:
    if: ${{ job.status == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t jakob999/vulnerable_app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push jakob999/vulnerable_app:latest
